### ISSUE TITLE
AUmfx needed

### ISSUE THREAD

**Issue by steveschow** [surge-synthesizer/stochas#7] opened 2020-08-11 04:38 UTC
The JUCE build flags need to be changed so that the AUmfx version will be built instead of or in addition to Instrument version.  the AUinst version is useless in LogicPro, which is primarily where AU is needed.  AUInst plugins cannot output midi in Logic Pro.  Instead the JUCE flags should be set to build the AUmfx version which makes more sense as a midi generation plugin.

**Comment by baconpaul** [comment] 2020-08-11 10:52
Sorry we had this working but have been shuffling things around (I actually used it in LPX as a test). Will figure out what to swap. Thanks!

**Comment by baconpaul** [comment] 2020-08-11 11:07
OK so @rudeog if I build the AU with IS_SYNTH FALSE then it works again as a midi plugin logic.

So I am guessing, on macOS, we need to build the AU that way and then the rest the other way?

Lemme bang that into the pipeline on macOS.

**Comment by rudeog** [comment] 2020-08-11 11:49
I think the safest thing is to create a separate AU build that only has not-synth. So for the rest of the MacOS builds (ie VST) is to have is-synth, and for Win (and probably Linux) to have is-synth.

**Comment by baconpaul** [comment] 2020-08-11 11:50
Alright @rudeog as suspected we sort of need to run cmake 'twice' on mac for this to work so I unpacked the install/build pipeline to do that and merged it on mac.

@steveschow in LPX 10.5.1 that lets me drop stochas in as a MIDI FX slot ahead of my synths no problem. Basically a channel strip that looks like this

<img width="408" alt="Screen Shot 2020-08-11 at 7 41 03 AM" src="https://user-images.githubusercontent.com/13387561/89893269-08fbdf80-dba6-11ea-9970-126df165f3c1.png">

**Comment by baconpaul** [comment] 2020-08-11 11:50
Ha @rudeog I was posting that I had done exactly that at the same tie as your comment

**Comment by baconpaul** [comment] 2020-08-11 11:57
Anyway @steveschow the new nightly (https://github.com/surge-synthesizer/stochas/releases/tag/Nightly) I just confirmed gives an AU which loads in LPX 10.5.1 in the midi fx slot. Can you confirm and then we can close this issue? Thanks!

**Comment by steveschow** [comment] 2020-08-11 17:52
seems to work now.  Thanks for big and fast response!

**Comment by baconpaul** [comment] 2020-08-11 19:39
Super!

**Closed by baconpaul** 2020-08-11 19:39 UTC
