### ISSUE TITLE
Stochas hangs in FLStudio when playing song finish and jumps to the beginning.

### ISSUE THREAD

**Issue by parduz** [surge-synthesizer/stochas#76] opened 2021-05-30 08:54 UTC
I've set a pattern in Stochas, made it start playing at 17th bar using the C6 key in its track.
Everything works well when i start/stop/jump around in the song, but when the bar reaches the end of the song and jumps back to the very beginning FLStudio hangs for about 4-5 seconds, with a peak in the CPU meter.
If meanwhile i press the stop button, at the end of that hangs i get a short "burst" of audio, then the song playing stops and i can recommence.
If i don't stop, after that short burst FL hangs definitely and i can only kill it.
I deleted one VST after all until everything worked as normal when i deleted Stockas.

I repeat: this happens only when the songs play jumps from the end to the beginning. Playing in patterns mode does not have any problem.

**Comment by rudeog** [comment] 2021-05-30 14:27
Is this FLStudio on Windows?
If so, can you share a flstudio project (or exact steps to create one).

**Comment by parduz** [comment] 2021-05-30 23:08
Sure, here it is.

[Stochas bug.zip](https://github.com/surge-synthesizer/stochas/files/6567031/Stochas.bug.zip)

**Comment by rudeog** [comment] 2021-05-31 21:56
Thanks for the project. I appreciate it. I've managed to reproduce this in the debugger. It seems to occur only with manual playback, and I get a bunch of assertions because the playback position is negative. Probably FL when looping back around allows this value to be negative. I should probably be able to fix this soon.

**Comment by parduz** [comment] 2021-06-01 00:17
Great! thanks!


>Probably FL when looping back around allows this value to be negative.
Could it 'cause delay compensation? I (vaguely) know that FL Studio manages the delay that each plugin "declares" to have.... 
Dunno, really :D

Thanks again.

**Comment by rudeog** [comment] 2021-06-01 16:32
It turns out that this is a problem with manual playback start position being later than current position when looping back. So it has nothing to do with FL studio specifically (also is a problem on other hosts), it's just that FL studio seems to have a worse reaction. I should hopefully have a fix for this today or tomorrow.

**Comment by rudeog** [comment] 2021-06-01 19:30
This is now fixed in the latest developer release.

**Comment by parduz** [comment] 2021-06-01 20:12
> This is now fixed in the latest developer release.

Is the latest [https://github.com/surge-synthesizer/stochas/releases/tag/developer](this one)?

'cause if is it, then the problem is still there.

**Comment by rudeog** [comment] 2021-06-01 20:45
Yep that should include it. The developer download link you should be looking at is https://github.com/surge-synthesizer/stochas/releases/download/developer/stochas_windows_installer.exe and you should see 1.3.5.HEAD.31e65cb when you go to the settings tab in Stochas. I just downloaded, installed it and tested against your test project (which was previously crashing, but now loops and plays fine).  If you are still seeing the issue with that version, then we'd have to see what other settings differ between our environments.

**Comment by parduz** [comment] 2021-06-01 23:15
You're right, my test project now works.
But, please, slide the pattern that starts Stochas to bar 6, and the last of the empy ones at bar 9 and it will hangs again:

![image](https://user-images.githubusercontent.com/9556348/120401299-f2469500-c33f-11eb-8112-2e8fa8f1fd5c.png)

**Comment by parduz** [comment] 2021-06-01 23:18
Also, pls check about the first note in the Stochas pattern being played double when the bar loops back and/or when it pass on the "play note" again.
To me is clearly audible that the first note is doubled.

Thanks :)

**Comment by rudeog** [comment] 2021-06-02 19:39
Ok, should be fixed now. I have opened a separate issue for the double triggering, as I was not able to isolate it, however I did reproduce it intermittently.

**Closed by rudeog** 2021-06-02 19:39 UTC
